### ISSUE TITLE
SRTP_AES_GCM support

### ISSUE THREAD

**Issue by Mnwa** [HyeonuPark/srtp#1]
Hi! Can you add aes-gcm policy support?

**Comment by HyeonuPark** [comment]
Hi! Gcm family requires openssl support which the srtp2-sys crate doesn't support currently. But I'm planning to rewrite its build script to support link to system library and openssl support.

**Comment by Mnwa** [comment]
Thanks for your response. Maybe you can help me with another problem? 
I try to read keying material from OpenSSL with this code:
```rust
    let rtp_policy = CryptoPolicy::default();
    let rtcp_policy = CryptoPolicy::default();

    let mut dtls_buf = vec![0; rtp_policy.master_len() * 2];
    ssl.export_keying_material(dtls_buf.as_mut_slice(), "EXTRACTOR-dtls_srtp", None)?;

    let pair = rtp_policy.extract_keying_material(dtls_buf.as_mut_slice());

   let srtp_reader =
        Srtp::new(SsrcType::AnyInbound, rtp_policy, rtcp_policy, pair.server).unwrap();
```

After that, I try to unprotected RTP message
```rust
match ssl_stream.get_mut().read(&mut buf).await {
    Ok(n) => {
        if n == 0 {
            return None;
        }
        buf.truncate(n);

        let mut buf = BytesMut::from(buf.as_slice());

        println!("{}", srtp_reader.unprotect(&mut buf).is_err());
    }
}
```
And it's return `true`, `AuthErr`. What am I doing wrong? Full example you can find [here](https://github.com/Mnwa/rs-streamer/blob/master/src/server/client.rs#L39)

**Comment by HyeonuPark** [comment]
Sorry for the insufficient documentation! Since it's the dtls server, inbound srtp should use the client key and outbound srtp should use the server key.

**Comment by Mnwa** [comment]
Np! I'm so sorry too. I forgot to tell, what I was trying to swap server and client keys, and the result is the same.

**Comment by HyeonuPark** [comment]
Maybe I found it. You're using the[SRTP_AES128_CM_SHA1_80](https://github.com/Mnwa/rs-streamer/blob/5391b976a563816fcb9ea702d3f8ea03ee3ea899/src/server/crypto.rs#L30) crypto policy so replace the `CryptoPolicy::default()` with `CryptoPolicy::AesCm128HmacSha1Bit80` and please let me know if it works.

**Comment by Mnwa** [comment]
The result is the same - `AuthFail` :(

**Comment by HyeonuPark** [comment]
Could you check the `ssl.selected_srtp_profile().unwrap().name()` within the `get_srtp()` function?

**Comment by Mnwa** [comment]
`println!("{}", ssl.selected_srtp_profile().unwrap().name());` prints `SRTP_AES128_CM_SHA1_80`

**Comment by HyeonuPark** [comment]
Could you share your current `client.rs`?

**Comment by Mnwa** [comment]
Yep. I pushed the last changes to the master. Actual `client` is [here](https://github.com/Mnwa/rs-streamer/blob/master/src/server/client.rs).

**Comment by HyeonuPark** [comment]
Honestly, I don't know :( I can't find any mistake on your code. This crate is made as a part of my WIP WebRTC SFU server, not published yet due to some legal issue, but _it works on my machine_ both on macos and linux.

Not sure it's the reason though, in my code I eagerly demux the STUN/DTLS/RT[C]P packets and only feed DTLS ones into the SSL stream. And yet I'm not sure if feeding RTCP packets into `.unprotect()` results such error.

Please let me know If you made any advance. I'm sorry that I can't help you much.

**Comment by Mnwa** [comment]
All ok! Thank you for the help!
